name: be-portainer-webhook

on:
  workflow_run:
    workflows: [ "be-docker-buildx-ci" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send Trigger
        run: |
          curl -X POST ${{ secrets.BE_PORTAINER_WEBHOOK_URL }}